### PR TITLE
Fixing bug in `GeoUtils.calcOrderedCoordinateDistances()`.

### LINKED ISSUE #449: `GeoUtils.calcOrderedCoordinateDistances()` doesn't return all `CoordinateDistances`
f5165363-e4ed-4e25-a7d9-ef141db005c9

If two points have the same distance to the base point, only one is returned.

### PR DESCRIPTION
**Pull request by staudtMarius**
Resolves #449

### CODE REVIEW

File: src/main/java/edu/ie3/util/geo/GeoUtils.java [hunk 1]
```diff
@@ -133,11 +133,12 @@ public static SortedSet<CoordinateDistance> getCoordinateDistances(
...
    * @return a sorted set of distances between the base and other coordinates
    */
-  public static SortedSet<CoordinateDistance> calcOrderedCoordinateDistances(
+  public static Set<CoordinateDistance> calcOrderedCoordinateDistances(
       Point baseCoordinate, Collection<Point> coordinates) {
     return coordinates.stream()
         .map(coordinate -> new CoordinateDistance(baseCoordinate, coordinate))
-        .collect(Collectors.toCollection(TreeSet::new));
+        .sorted(Comparator.comparing(CoordinateDistance::getDistance))
+        .collect(Collectors.toCollection(LinkedHashSet::new));
```
Comment (sebastian-peter) [inline src/main/java/edu/ie3/util/geo/GeoUtils.java:141]: I think it would also be fine to just return a `List` here (not any `Collection` though since order needs to be preserved). We would only need a (hash)set here if we needed fast checks of containment, which I think we don't.

**Review by sebastian-peter — CHANGES_REQUESTED** [review]
Only one small remark.

**Review by sebastian-peter — APPROVED** [review]
