### PR TITLE
Added tolerances and convenience methods, fixed equality check

### LINKED ISSUE #49: Adapt QuantityUtil with tolerance values and convenience methods
The following test fails, as convertedQ1 now holds a BigDecimal value instead of a double value, which makes the equals check fail.
```
@Test
public void test() {
     ComparableQuantity<Length> q1 = Quantities.getQuantity(0.0001d, MetricPrefix.KILO(Units.METRE));
     ComparableQuantity<Length> convertedQ1 = q1.to(Units.METRE);
     ComparableQuantity<Length> q2 = Quantities.getQuantity(0.1d, Units.METRE);
     ComparableQuantity<Length> convertedQ2 = q2.to(Units.METRE);
     assertEquals(convertedQ1, convertedQ2);
}
```
So, we need to do our own alternative for an equality check: Checking unit and value individually. While doing so, we can use tolerance values as well as now it's in our control. Yay.

### PR DESCRIPTION
**Pull request by mia-krause**
fixes #49 

Please check if you feel like those default values are fitting!

### CODE REVIEW

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java [hunk 1]
```diff
@@ -16,6 +16,11 @@
 
 /** Offers useful methods to handle {@link Quantity}s */
 public class QuantityUtil {
+
+  private static final double DEFAULT_ABSOLUTE_TOLERANCE = 0d;
+  private static final double DEFAULT_RELATIVE_TOLERANCE = 0.00000001d;
+  private static final double DEFAULT_ANGLE_TOLERANCE = 0.001d;
```
Comment (ckittl) [inline src/main/java/edu/ie3/util/quantities/QuantityUtil.java:22]: Why did you choose different tolerances here? I would have assumed, that all methods are default very strict (not accepting any tolerances).

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java [hunk 2]
```diff
@@ -31,6 +36,24 @@ private QuantityUtil() {
...
+   * QuantityUtil#considerablyAbsEqual(Quantity, Quantity, double)} with a default tolerance of
+   * {@value DEFAULT_ABSOLUTE_TOLERANCE}
+   *
+   * @param a First quantity to compare
+   * @param b Second quantity to compare
+   * @param <Q> Type of Quantity
+   * @return true, if both quantities' values differ less then the given tolerance else false (based
+   *     on a's unit)
+   */
+  public static <Q extends Quantity<Q>> boolean considerablyAbsEqual(Quantity<Q> a, Quantity<Q> b) {
```
Comment (ckittl) [inline src/main/java/edu/ie3/util/quantities/QuantityUtil.java:53]: As the indriya lib is distinguishing between `equals` and `isEquivalentTo`, I would vote for adapting to this taxonomy. In my mind "is the same" and "equals" colloquial is the same. Therefore, renaming the `considerablyEqual` methods to `considerablyEquivalentTo` and `isTheSame` to `equals` would clarify, what the methods actually do. Having the downside... to be breaking.

@johanneshiry What are your thoughts on this?

**Review by ckittl — CHANGES_REQUESTED** [review]

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java (hunk 1 above)
Comment (mia-krause) [reply src/main/java/edu/ie3/util/quantities/QuantityUtil.java:22]: I didn't have any base except for the angle, where I used the one from the tests, so I used 0 for absolute tolerance as this would mimic complete equality the best. If all are set to 0, should we keep the three tolerances or combine them into one, in case that we want to change one but not the others in the future?

Comment (ckittl) [reply src/main/java/edu/ie3/util/quantities/QuantityUtil.java:22]: I would join them, as this is what the "original" equal methods do.

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java (hunk 2 above)
Comment (mia-krause) [reply src/main/java/edu/ie3/util/quantities/QuantityUtil.java:53]: I would like that! Ideally, we'd find a good naming distinction between `considerablyAbsEqual` and `isTheSameConsideringEmpty` as well.

As 2.0 is breaking anyway, I feel like it wouldn't be that bad?

Comment (ckittl) [reply src/main/java/edu/ie3/util/quantities/QuantityUtil.java:53]: I think, we haven't decided, yet, if we will schedule this for a major or a minor version increase. However, from my point of view, it is better to break something irritating now, than sticking to spreading this.

**Comment by johanneshiry** [comment]
@mia-krause @ckittl can someone of you tell me what's the current status here? I would like to publish a new minor release to prepare power system data model release 2.0 and I would prefer closing this before

**Comment by ckittl** [comment]
don't know

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java [hunk 3]
```diff
@@ -31,6 +34,25 @@ private QuantityUtil() {
...
+   * The comparison is made on the absolute difference of both quantities' value. Both quantities
+   * are converted into a's unit before the comparison. Internally calls {@link
+   * QuantityUtil#isAbsolutelyEquivalent(Quantity, Quantity, double)} with a default tolerance of
+   * {@value DEFAULT_TOLERANCE}
+   *
+   * @param a First quantity to compare
+   * @param b Second quantity to compare
+   * @param <Q> Type of Quantity
+   * @return true, if both quantities' values differ less then the given tolerance else false (based
+   *     on a's unit)
```
Comment (ckittl) [inline src/main/java/edu/ie3/util/quantities/QuantityUtil.java:49]:
```suggestion
   * Compares two {@link Quantity}s, if they are <b>equivalent</b> considering both quantities magnitude. This is foremost important for
   * {@link tech.units.indriya.quantity.NumberQuantity}s with internal big decimal or double values.
   * The comparison is made on the absolute difference of both quantities' value. Both quantities
   * are converted into {@code a}'s unit before the comparison. Internally calls {@link
   * QuantityUtil#isAbsolutelyEquivalent(Quantity, Quantity, double)} with a default tolerance of
   * {@value DEFAULT_TOLERANCE}
   *
   * @param a First quantity to compare
   * @param b Second quantity to compare
   * @param <Q> Type of Quantity
   * @return true, if both quantities' do not differ in values (considering no tolerance), else false
```

Comment (ckittl) [reply src/main/java/edu/ie3/util/quantities/QuantityUtil.java:49]: Please try and adapt the remaining JavaDocs accordingly. To me it is important to highlight the difference to the concept of equality.

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java [hunk 4]
```diff
@@ -31,6 +34,25 @@ private QuantityUtil() {
...
+   */
+  public static <Q extends Quantity<Q>> boolean isAbsolutelyEquivalent(
```
Comment (ckittl) [inline src/main/java/edu/ie3/util/quantities/QuantityUtil.java:51]:
```suggestion
  public static <Q extends Quantity<Q>> boolean isEquivalentAbs(
```

Sorry to once again popping in with some kind of esoterically discussions about naming. As the attribute "absolutely" is also used more or less colloquial (e.g. "Your two twins look absolutely the same."), the method name could be a bit misleading. How do you feel with my suggestion?

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java [hunk 5]
```diff
@@ -41,9 +63,10 @@ private QuantityUtil() {
    * @param b Second quantity to compare
    * @param absQuantityTolerance Permissible absolute tolerance
    * @param <Q> Type of Quantity
-   * @return true, if both quantities' values differ less then the given tolerance else false
+   * @return true, if both quantities' values differ less then the given tolerance else false (based
+   *     on a's unit)
    */
-  public static <Q extends Quantity<Q>> boolean considerablyAbsEqual(
+  public static <Q extends Quantity<Q>> boolean isAbsolutelyEquivalent(
```
Comment (ckittl) [inline src/main/java/edu/ie3/util/quantities/QuantityUtil.java:69]: Please keep the old implementation `considerablyAbsEqual`, mark it as deprecated and call the new function instead. This could really help us not breaking too much.

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java [hunk 6]
```diff
@@ -52,6 +75,24 @@ private QuantityUtil() {
...
+   * value. Both quantities are converted into a's unit before the comparison. Internally calls
+   * {@link QuantityUtil#isRelativelyEquivalent(Quantity, Quantity, double)} with a default
+   * tolerance of {@value DEFAULT_TOLERANCE}
+   *
+   * @param a First quantity to compare
+   * @param b Second quantity to compare
+   * @param <Q> Type of Quantity
+   * @return true, if both quantities' values differ less then the given tolerance else false
+   */
+  public static <Q extends Quantity<Q>> boolean isRelativelyEquivalent(
```
Comment (ckittl) [inline src/main/java/edu/ie3/util/quantities/QuantityUtil.java:91]:
```suggestion
  public static <Q extends Quantity<Q>> boolean isEquivalentRel(
```

See discussion above.

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java [hunk 7]
```diff
@@ -52,6 +75,24 @@ private QuantityUtil() {
     return Math.abs(aVal - bVal) <= absQuantityTolerance;
   }
 
+  /**
+   * Compares two {@link Quantity}s, if they are considerably equal. This is foremost important for
```
Comment (ckittl) [inline src/main/java/edu/ie3/util/quantities/QuantityUtil.java:79]: Please adapt JavaDoc to highlight the concept of equivalence in contrast to equality.

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java [hunk 8]
```diff
@@ -64,7 +105,7 @@ private QuantityUtil() {
    * @param <Q> Type of Quantity
    * @return true, if both quantities' values differ less then the given tolerance else false
    */
-  public static <Q extends Quantity<Q>> boolean considerablyRelEqual(
+  public static <Q extends Quantity<Q>> boolean isRelativelyEquivalent(
```
Comment (ckittl) [inline src/main/java/edu/ie3/util/quantities/QuantityUtil.java:108]: See above (naming and `@Deprecated`).

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java [hunk 9]
```diff
@@ -73,6 +114,23 @@ private QuantityUtil() {
     return (Math.abs(aVal - bVal) / Math.abs(aVal)) <= relQuantityTolerance;
   }
 
+  /**
+   * Compares two {@link Angle} {@link Quantity}s, if they are considerably equal. This is foremost
```
Comment (ckittl) [inline src/main/java/edu/ie3/util/quantities/QuantityUtil.java:118]: See above.

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java [hunk 10]
```diff
@@ -111,16 +169,18 @@ public static boolean considerablyEqualAngle(
...
    * type {@link EmptyQuantity} or if they are equal in value <b>and</b> Unit. The type of the value
-   * does not matter. Throws a NullPointerException if the any quantity is null, as null is not to
-   * be expected as any known empty value should be replaced by an EmptyQuantity.
+   * does not matter. Throws a NullPointerException if any quantity is null, as null is not to be
+   * expected as any known empty value should be replaced by an EmptyQuantity.<br>
+   * Internally calls {@link QuantityUtil#equals(Quantity, Quantity, double)} with a default
+   * tolerance of {@value DEFAULT_TOLERANCE}
    *
    * <p>isTheSameConsideringEmpty(1 km, 1000 m) // false <br>
    * isTheSameConsideringEmpty(1.0 km, 1 km) //true
```
Comment (ckittl) [inline src/main/java/edu/ie3/util/quantities/QuantityUtil.java:186]:
```suggestion
   * <p>equals(1 km, 1000 m) // false <br>
   * equals(1.0 km, 1 km) //true
```

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java [hunk 11]
```diff
@@ -131,42 +191,89 @@ public static boolean quantityIsEmpty(Quantity<?> that) {
...
+  }
+
+  /**
+   * Compares two {@link Quantity}s, if they are equal. Returns true only if both quantities are of
+   * type {@link EmptyQuantity} or if they are equal in value <b>and</b> Unit. The type of the value
+   * does not matter. Throws a NullPointerException if any quantity is null, as null is not to be
+   * expected as any known empty value should be replaced by an EmptyQuantity.
+   *
+   * <p>isTheSameConsideringEmpty(1 km, 1000 m) // false <br>
+   * isTheSameConsideringEmpty(1.0 km, 1 km) //true
```
Comment (ckittl) [inline src/main/java/edu/ie3/util/quantities/QuantityUtil.java:205]:
```suggestion
   * <p>equals(1 km, 1000 m) // false <br>
   * equals(1.0 km, 1 km) //true
```

Additionally, please provide an example, that is actually taking the tolerance argument and also utilizes it.

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java [hunk 12]
```diff
@@ -131,42 +191,89 @@ public static boolean quantityIsEmpty(Quantity<?> that) {
...
    *
    * @param a First quantity to compare
    * @param b Second quantity to compare
    * @param <Q> Type of the Quantity
-   * @return true, if both are an EmptyQuantity or if they are equivalent
+   * @return true, if both are an EmptyQuantity or both quantities' values differ less then the
+   *     given tolerance else false (based on a's unit)
    * @throws NullPointerException if any quantity is null
    */
   public static <Q extends Quantity<Q>> boolean isEquivalentConsideringEmpty(
```
Comment (ckittl) [inline src/main/java/edu/ie3/util/quantities/QuantityUtil.java:245]: Please move the equivalence methods upwards, in order to have equivalence and equality methods closely together.

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java [hunk 13]
```diff
@@ -131,42 +191,89 @@ public static boolean quantityIsEmpty(Quantity<?> that) {
...
-   * empty value should be replaced by an EmptyQuantity.
+   * NullPointerException if any quantity is null, as null is not to be expected as any known empty
+   * value should be replaced by an EmptyQuantity. Internally calls {@link
+   * QuantityUtil#isEquivalentConsideringEmpty(ComparableQuantity, ComparableQuantity, double)} with
+   * a default tolerance of {@value DEFAULT_TOLERANCE}
    *
-   * <p>isEquivalentConsideringEmpty(1 km, 1000 m)// true <br>
-   * isEquivalentConsideringEmpty(1.0 km, 1 km) // true
+   * <p>isEquivalentConsideringEmpty(1 km, 1000 m, 0)// true <br>
+   * isEquivalentConsideringEmpty(1.0 km, 1 km, 0) // true
```
Comment (ckittl) [inline src/main/java/edu/ie3/util/quantities/QuantityUtil.java:236]:
```suggestion
   * <p>isEquivalentConsideringEmpty(1 km, 1000 m)// true <br>
   * isEquivalentConsideringEmpty(1.0 km, 1 km) // true
```

**Review by ckittl — CHANGES_REQUESTED** [review]

**Review by ckittl — APPROVED** [review]

File: src/main/java/edu/ie3/util/quantities/QuantityUtil.java (hunk 5 above)
Comment (ckittl) [reply src/main/java/edu/ie3/util/quantities/QuantityUtil.java]: Sorry for this. Just realized, that it was "former me", that suggested renaming. 😞
